name: Build IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: run ipabuild.sh
      run:
        chmod +x ./ipabuild.sh
        ./ipabuild.sh
      shell: bash
    
