name: Build dirtyZero

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos
      CPATH: :/opt/procursus/include
      LIBRARY_PATH: :/opt/procursus/lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Haalt ook Theos submodules binnen

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            perl \
            ldid \
            fakeroot \
            clang \
            make \
            git \
            curl \
            unzip \
            zip

      - name: Set up Theos
        run: |
          if [ ! -d "theos" ]; then
            git clone --recursive https://github.com/theos/theos.git theos
            # Optioneel: clone andere vendoren als je ze gebruikt
            git clone https://github.com/theos/sdks.git theos/sdks
          fi

      - name: Build dirtyZero package
        run: make package FINALPACKAGE=1 STRIP=0
