name: Xcode - Build

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs: 
      release__nightly:
        description: Create a nightly release
        type: boolean
        required: false

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest
    env:
      scheme: dirtyZero
      archive_path: archive
    outputs:
      scheme: ${{ steps.scheme.outputs.scheme }}
      archive_path: ${{ env.archive_path }}

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set Scheme
        id: scheme
        run: |
          if [ $scheme = default ]
          then
            scheme_list=$(xcodebuild -list -json | tr -d "\n")
            scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
            echo Using default scheme: $scheme
          else
            echo Using configured scheme: $scheme
          fi
          echo "scheme=$scheme" >> $GITHUB_OUTPUT
      - name: Set filetype_parameter
        id: filetype_parameter
        run: |
          filetype_parameter=`ls -A | grep -i \\.xcworkspace\$ && echo workspace || echo project`
          echo "filetype_parameter=$filetype_parameter" >> $GITHUB_OUTPUT
      - name: Set file_to_build
        id: file_to_build
        run: |
          file_to_build=`ls -A | grep -i \\.xcworkspace\$ || ls -A | grep -i \\.xcodeproj\$`
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo "file_to_build=$file_to_build" >> $GITHUB_OUTPUT
      - name: Archive
        env:
          scheme: ${{ steps.scheme.outputs.scheme }}
          filetype_parameter: ${{ steps.filetype_parameter.outputs.filetype_parameter }}
          file_to_build: ${{ steps.file_to_build.outputs.file_to_build }}
        run: xcodebuild archive -archivePath "$archive_path" -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -sdk iphoneos -arch arm64 -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
      - name: Tar Build Artifact
        run: tar -cvf "$archive_path.xcarchive.tar" "$archive_path.xcarchive"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.archive_path }}.xcarchive.tar
          path: ${{ env.archive_path }}.xcarchive.tar

  package:
    name: Create fake-signed ipa
    runs-on: ubuntu-latest
    needs: [build]
    env:
      scheme: ${{ needs.build.outputs.scheme }}
      archive_path: ${{ needs.build.outputs.archive_path }}
    outputs:
      artifact: ${{ env.scheme }}.ipa

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.archive_path }}.xcarchive.tar
      - name: Extract Build Artifact
        run: tar -xf "$archive_path.xcarchive.tar"
      - name: Install ldid
        run: |
          if [ `uname -s` = "Linux" ]; then
            curl -sSL -o /usr/local/bin/ldid "${{ github.server_url }}/ProcursusTeam/ldid/releases/latest/download/ldid_linux_`uname -m`"
            chmod +x /usr/local/bin/ldid
          elif [ `uname -s` = "Darwin" ]; then
            brew install ldid
          else
            exit 1
          fi
      - name: Fakesign
        run: |
          ls "$archive_path.xcarchive/Products/Applications/dirtyZero.app"
          find "$archive_path.xcarchive/Products/Applications/$scheme.app" -type d -path '*/Frameworks/*.framework' -exec ldid -Sentitlements.xml \{\} \;
          ldid -Sentitlements.xml "$archive_path.xcarchive/Products/Applications/$scheme.app"
      - name: Create IPA
        run: |
          mv "$archive_path.xcarchive/Products/Applications" Payload
          zip -r "$scheme.ipa" "Payload" -x "._*" -x ".DS_Store" -x "__MACOSX"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.scheme }}.ipa
          path: ${{ env.scheme }}.ipa
      - name: Move IPA to root of repository
        run: |
          mkdir -p downloads
          mv "$scheme.ipa" "$GITHUB_WORKSPACE/downloads/"
      - name: Commit and push IPA to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add "$GITHUB_WORKSPACE/downloads/$scheme.ipa"
          git commit -m "Add IPA build artifact"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  sign:
    name: Sign IPA with certificate
    runs-on: macos-latest   # Use macOS runner for `security` commands
    needs: [package]
    env:
      KEYCHAIN_PASSWORD: buildpassword
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decode and prepare signing files
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 -d > signing.p12
          echo "${{ secrets.PROVISION_BASE64 }}" | base64 -d > profile.mobileprovision

      - name: Create temporary keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import signing.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign -A -f pkcs12
          security list-keychains -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Copy provisioning profile into app
        run: |
          cp downloads/${{ env.scheme }}.ipa unsigned.ipa
          unzip unsigned.ipa -d unpacked
          cp profile.mobileprovision unpacked/Payload/${{ env.scheme }}.app/embedded.mobileprovision

      - name: Create entitlements.plist
        run: |
          cat > entitlements.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>get-task-allow</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Real sign embedded frameworks and main executable with ldid
        run: |
          # Install ldid if needed
          if ! command -v ldid &> /dev/null; then
            brew install ldid
          fi

          APP_PATH=unpacked/Payload/${{ env.scheme }}.app
          find "$APP_PATH/Frameworks" -type d -name '*.framework' -exec ldid -Sentitlements.plist -Ksigning.p12 -Csigning.p12 {} \;
          EXECUTABLE_NAME=$(defaults read "$APP_PATH/Info.plist" CFBundleExecutable)
          ldid -SEntitlements.plist -Ksigning.p12 -Csigning.p12 "$APP_PATH/$EXECUTABLE_NAME"

      - name: Repackage IPA
        run: |
          cd unpacked
          zip -r ../${{ env.scheme }}.ipa Payload -x "._*" -x ".DS_Store" -x "__MACOSX"
          cd ..

      - name: Replace IPA in downloads folder
        run: |
          mv ${{ env.scheme }}.ipa downloads/${{ env.scheme }}.ipa

      - name: Cleanup
        run: |
          security delete-keychain build.keychain



  release__nightly:
    name: Nightly Release
    permissions:
      contents: write
    if: inputs.release__nightly || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [package]
    concurrency:
      group: release__nightly
      cancel-in-progress: true

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package.outputs.artifact }}
      - name: Nightly Release
        uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          body: |
            This is a nightly release [created automatically with GitHub Actions workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}).
          files: |
            ${{ needs.package.outputs.artifact }}
