name: Build dirtyZero

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos
      CPATH: :/opt/procursus/include
      LIBRARY_PATH: :/opt/procursus/lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            perl \
            fakeroot \
            clang \
            make \
            git \
            curl \
            unzip \
            zip \
            libssl-dev \
            libplist-dev \
            libxml2-dev \
            libtool \
            autoconf \
            automake

      - name: Install ldid from source
        run: |
          git clone https://github.com/ProcursusTeam/ldid.git
          cd ldid
          git submodule update --init
          make
          sudo cp ldid /usr/local/bin
          cd ..

      - name: Set up Theos
        run: |
          if [ ! -d "theos" ]; then
            git clone --recursive https://github.com/theos/theos.git theos
          fi

          if [ ! -d "theos/sdks" ]; then
            git clone https://github.com/theos/sdks.git theos/sdks
          fi


      - name: Build dirtyZero package
        run: make package FINALPACKAGE=1 STRIP=0
